setup.py:
  required:
    - project_name
    - author
    - author_email
  content: >
    from setuptools import setup

    setup(name='{project_name}',
          version='0.1.0',
          description='',
          url='',
          author='{author}',
          author_email='{author_email}',
          license='',
          packages=[]
          )
requirements.txt:
  required: null
  content: null
